# Generated by Django 5.0.6 on 2025-03-06 12:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_traininghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(help_text="Faoliyat nomi (masalan, 'Operatsiya', 'Malaka oshirish', 'Xizmat safari')", max_length=255)),
                ('activity_type', models.CharField(choices=[('training', 'Malaka oshirish'), ('operation', 'Operatsiya'), ('business_trip', 'Xizmat safari'), ('certification', 'Sertifikat olish'), ('conference', 'Konferensiya'), ('workshop', 'Amaliy mashg‘ulot'), ('other', 'Boshqa')], default='training', help_text='Faoliyat turi', max_length=50)),
                ('description', models.TextField(blank=True, help_text="Faoliyat haqida qisqacha tavsif (masalan, 'Appendektomiya operatsiyasi', 'Kardiologiya kursi')")),
                ('location_name', models.CharField(blank=True, help_text="Faoliyat joyi (masalan, 'Toshkent Tibbiyot Akademiyasi', 'Parij klinikasi')", max_length=255)),
                ('city', models.CharField(blank=True, help_text="Shahar (masalan, 'Toshkent', 'Parij')", max_length=100)),
                ('country', models.CharField(blank=True, help_text="Davlat (masalan, 'O‘zbekiston', 'Fransiya')", max_length=100)),
                ('start_date', models.DateField(help_text='Faoliyat boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, help_text='Faoliyat tugash sanasi (agar davomiy bo‘lmasa)', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Faoliyat muvaffaqiyatli yakunlanganmi?')),
                ('result_details', models.TextField(blank=True, help_text="Natija haqida qo‘shimcha ma'lumot (masalan, 'Sertifikat olindi', 'Operatsiya muvaffaqiyatli')")),
                ('certificate_file', models.FileField(blank=True, help_text='Sertifikat yoki tasdiqlovchi hujjat (PDF, JPG va h.k.)', null=True, upload_to='activity_certificates/')),
                ('additional_files', models.FileField(blank=True, help_text='Qo‘shimcha hujjatlar (masalan, hisobot, fotosurat)', null=True, upload_to='activity_documents/')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Faoliyat xarajati (so‘mda yoki boshqa valyutada)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('funded_by_clinic', models.BooleanField(default=False, help_text='Klinika tomonidan moliyalashtirilganmi?')),
                ('expense_report', models.FileField(blank=True, help_text='Xarajat hisoboti (agar mavjud bo‘lsa)', null=True, upload_to='expense_reports/')),
                ('related_operation', models.CharField(blank=True, help_text="Agar operatsiya bo‘lsa, uning turi (masalan, 'Appendektomiya')", max_length=255)),
                ('supervisor', models.CharField(blank=True, help_text="Rahbar yoki trener ismi (masalan, 'Dr. Ahmadov')", max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Qo‘shimcha eslatmalar yoki izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Yozuv yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Oxirgi yangilangan sana')),
                ('user', models.ForeignKey(help_text='Faoliyat bilan bog‘liq xodim', on_delete=django.db.models.deletion.CASCADE, related_name='activity_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xodim faoliyat tarixi',
                'verbose_name_plural': 'Xodim faoliyat tarixlari',
                'ordering': ['-start_date'],
            },
        ),
        migrations.DeleteModel(
            name='TrainingHistory',
        ),
    ]
