# Generated by Django 5.1.7 on 2025-03-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_employeeactivityhistory_delete_traininghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeactivityhistory',
            name='start_date',
            field=models.DateField(blank=True, help_text='Faoliyat boshlanish sanasi', null=True),
        ),
    ]
