# Generated by Django 5.1.7 on 2025-03-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_employeeactivityhistory_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Xodim ID', max_length=50, null=True),
        ),
    ]
