# Generated by Django 5.1.5 on 2025-01-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Foydalanuvchi faol yoki faol emasligini belgilaydi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Foydalanuvchi admin sahifasiga kira oladimi'),
        ),
    ]
