# Generated by Django 5.0.6 on 2025-03-05 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=dict, help_text="Har xil tillarda e'lon sarlavhasi (JSON formatda)")),
                ('content', models.JSONField(default=dict, help_text="Har xil tillarda e'lon mazmuni (JSON formatda)")),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='Chop etilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Oxirgi tahrir qilingan sana')),
                ('is_published', models.BooleanField(default=False, help_text='Chop etilganmi?')),
                ('views_count', models.PositiveIntegerField(default=0, help_text="E'lon qancha marta ko'rilgan")),
                ('author', models.ForeignKey(blank=True, help_text="E'lon muallifi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=dict, help_text='Har xil tillarda yangiliklar sarlavhasi (JSON formatda)')),
                ('content', models.JSONField(default=dict, help_text='Har xil tillarda yangilik mazmuni (JSON formatda)')),
                ('image', models.ImageField(blank=True, help_text='Yangiliklar rasmi', null=True, upload_to='news_images/')),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='Chop etilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Oxirgi tahrir qilingan sana')),
                ('is_published', models.BooleanField(default=False, help_text='Chop etilganmi?')),
                ('views_count', models.PositiveIntegerField(default=0, help_text="Yangilik qancha marta ko'rilgan")),
                ('author', models.ForeignKey(blank=True, help_text='Yangilik muallifi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Foydalanuvchining to'liq ismi", max_length=255)),
                ('phone_number', models.CharField(help_text='Foydalanuvchining telefon raqami', max_length=20)),
                ('text', models.TextField(help_text='Izoh matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Izoh qoldirilgan sana')),
                ('news', models.ForeignKey(help_text='Izoh berilgan yangilik', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
