# Generated by Django 5.1.5 on 2025-01-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Doctor A haqida ma'lumot sarlavhasi", max_length=255)),
                ('description', models.TextField(help_text="Doctor A haqida batafsil ma'lumot")),
                ('image', models.ImageField(help_text="Doctor A haqida ma'lumot rasmi", upload_to='doctor_a/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Doctor A haqida ma'lumot",
                'verbose_name_plural': "Doctor A haqida ma'lumotlar",
            },
        ),
        migrations.CreateModel(
            name='MainPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="1920x180 o'lchamdagi asosiy sahifa banner rasmi", upload_to='banners/')),
                ('description', models.TextField(blank=True, help_text='Rasm haqida qisqacha tavsif', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asosiy sahifa banneri',
                'verbose_name_plural': 'Asosiy sahifa bannerlari',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='Sayt nomini kiriting', max_length=255)),
                ('logo_dark', models.ImageField(blank=True, help_text='Dark rejim uchun logotip', null=True, upload_to='logos/')),
                ('logo_light', models.ImageField(blank=True, help_text='Light rejim uchun logotip', null=True, upload_to='logos/')),
                ('contact_email', models.EmailField(blank=True, help_text='Aloqa uchun email manzil', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Aloqa uchun telefon raqami', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Kompaniya manzili', null=True)),
                ('maintenance_mode', models.BooleanField(default=False, help_text="Saytni texnik xizmat ko'rsatish rejimiga o'tkazish")),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook sahifa URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter sahifa URL', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram sahifa URL', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn sahifa URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt Sozlamalari',
                'verbose_name_plural': 'Sayt Sozlamalari',
            },
        ),
    ]
