# Generated by Django 5.1.5 on 2025-01-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Telefon raqami (+998...) formatda kiriting', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Telefon raqam haqida qisqacha tavsif', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aloqa Telefoni',
                'verbose_name_plural': 'Aloqa Telefonlari',
            },
        ),
    ]
