# Generated by Django 5.1.5 on 2025-01-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_contactphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorainfo',
            name='description',
            field=models.JSONField(default=dict, help_text='Har xil tillarda batafsil tavsif (JSON formatda)'),
        ),
        migrations.AlterField(
            model_name='doctorainfo',
            name='title',
            field=models.JSONField(default=dict, help_text='Har xil tillarda sarlavha (JSON formatda)'),
        ),
        migrations.AlterField(
            model_name='mainpagebanner',
            name='description',
            field=models.JSONField(default=dict, help_text='Har xil tillarda rasm tavsifi (JSON formatda)'),
        ),
    ]
