# Generated by Django 5.1.5 on 2025-01-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_alter_doctorainfo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactphone',
            name='description',
            field=models.JSONField(default=dict, help_text='Har xil tillarda telefon raqami haqida qisqacha tavsif (JSON formatda)'),
        ),
    ]
