# Generated by Django 5.1.5 on 2025-01-27 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_partner_announcement_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Yaratilgan sana'),
            preserve_default=False,
        ),
    ]
