from django.urls import path
from django.views.generic import RedirectView

from .views import (
    AboutStyleTwoView,
    AnnouncementLandingDetailView,
    AnnouncementRightSidebarView,
    BlogRightSidebarView,
    ContactStyleTwoView,
    DoctorGridView,
    DoctorLandingDetailView,
    EquipmentLandingDetailView,
    EquipmentLeftSidebarView,
    LandingPageV1View,
    NewsLandingDetailView,
    ServicesOverviewView,
    VideosLandingView,
)

urlpatterns = [
    path("", LandingPageV1View.as_view(), name="landing-v1"),
    path("v1/", RedirectView.as_view(pattern_name="landing-v1", permanent=True)),

    path("about/", AboutStyleTwoView.as_view(), name="landing-v1-about"),
    path("services/", ServicesOverviewView.as_view(), name="landing-v1-services"),
    path("videos/", VideosLandingView.as_view(), name="landing-v1-videos"),
    path("doctors/", DoctorGridView.as_view(), name="landing-v1-doctors"),
    path("doctors/<int:pk>/", DoctorLandingDetailView.as_view(), name="landing-v1-doctor-detail"),
    path("news/", BlogRightSidebarView.as_view(), name="landing-v1-blog"),
    path("news/<int:pk>/", NewsLandingDetailView.as_view(), name="landing-v1-news-detail"),
    path("announcements/", AnnouncementRightSidebarView.as_view(), name="landing-v1-announcements"),
    path("announcements/<int:pk>/", AnnouncementLandingDetailView.as_view(), name="landing-v1-announcement-detail"),
    path("equipment/", EquipmentLeftSidebarView.as_view(), name="landing-v1-equipment"),
    path("equipment/<int:pk>/", EquipmentLandingDetailView.as_view(), name="landing-v1-equipment-detail"),
    path("contact/", ContactStyleTwoView.as_view(), name="landing-v1-contact"),
    path("blog/", RedirectView.as_view(pattern_name="landing-v1-blog", permanent=True)),
    path("about-style-two.html", RedirectView.as_view(pattern_name="landing-v1-about", permanent=True)),
    path("blog-right-sidebar.html", RedirectView.as_view(pattern_name="landing-v1-blog", permanent=True)),
    path(
        "announcements-right-sidebar.html",
        RedirectView.as_view(pattern_name="landing-v1-announcements", permanent=True),
    ),
    path("doctor-grid.html", RedirectView.as_view(pattern_name="landing-v1-doctors", permanent=True)),
    path("contact-style-two.html", RedirectView.as_view(pattern_name="landing-v1-contact", permanent=True)),
    path("blog-left-sidebar.html", RedirectView.as_view(pattern_name="landing-v1-equipment", permanent=True)),

    path("v1/about/", RedirectView.as_view(pattern_name="landing-v1-about", permanent=True)),
    path("v1/services/", RedirectView.as_view(pattern_name="landing-v1-services", permanent=True)),
    path("v1/videos/", RedirectView.as_view(pattern_name="landing-v1-videos", permanent=True)),
    path("v1/doctors/", RedirectView.as_view(pattern_name="landing-v1-doctors", permanent=True)),
    path("v1/doctors/<int:pk>/", RedirectView.as_view(pattern_name="landing-v1-doctor-detail", permanent=True)),
    path("v1/news/", RedirectView.as_view(pattern_name="landing-v1-blog", permanent=True)),
    path("v1/news/<int:pk>/", RedirectView.as_view(pattern_name="landing-v1-news-detail", permanent=True)),
    path("v1/announcements/", RedirectView.as_view(pattern_name="landing-v1-announcements", permanent=True)),
    path(
        "v1/announcements/<int:pk>/",
        RedirectView.as_view(pattern_name="landing-v1-announcement-detail", permanent=True),
    ),
    path("v1/equipment/", RedirectView.as_view(pattern_name="landing-v1-equipment", permanent=True)),
    path("v1/equipment/<int:pk>/", RedirectView.as_view(pattern_name="landing-v1-equipment-detail", permanent=True)),
    path("v1/contact/", RedirectView.as_view(pattern_name="landing-v1-contact", permanent=True)),
    path("v1/blog/", RedirectView.as_view(pattern_name="landing-v1-blog", permanent=True)),
    path("v1/about-style-two.html", RedirectView.as_view(pattern_name="landing-v1-about", permanent=True)),
    path("v1/blog-right-sidebar.html", RedirectView.as_view(pattern_name="landing-v1-blog", permanent=True)),
    path(
        "v1/announcements-right-sidebar.html",
        RedirectView.as_view(pattern_name="landing-v1-announcements", permanent=True),
    ),
    path("v1/doctor-grid.html", RedirectView.as_view(pattern_name="landing-v1-doctors", permanent=True)),
    path("v1/contact-style-two.html", RedirectView.as_view(pattern_name="landing-v1-contact", permanent=True)),
    path("v1/blog-left-sidebar.html", RedirectView.as_view(pattern_name="landing-v1-equipment", permanent=True)),
]
