# Generated by Django 5.0.6 on 2025-01-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=dict, help_text="Har xil tillarda e'lon sarlavhasi (JSON formatda)")),
                ('content', models.JSONField(default=dict, help_text="Har xil tillarda e'lon mazmuni (JSON formatda)")),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='Chop etilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Oxirgi tahrir qilingan sana')),
                ('is_published', models.BooleanField(default=False, help_text='Chop etilganmi?')),
                ('views_count', models.PositiveIntegerField(default=0, help_text="E'lon qancha marta ko'rilgan")),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Telefon raqami (+998...) formatda kiriting', max_length=20)),
                ('description', models.JSONField(default=dict, help_text='Har xil tillarda telefon raqami haqida qisqacha tavsif (JSON formatda)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aloqa Telefoni',
                'verbose_name_plural': 'Aloqa Telefonlari',
            },
        ),
        migrations.CreateModel(
            name='DoctorAInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=dict, help_text='Har xil tillarda sarlavha (JSON formatda)')),
                ('description', models.JSONField(default=dict, help_text='Har xil tillarda batafsil tavsif (JSON formatda)')),
                ('image', models.ImageField(help_text="Doctor A haqida ma'lumot rasmi", upload_to='doctor_a/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Doctor A haqida ma'lumot",
                'verbose_name_plural': "Doctor A haqida ma'lumotlar",
            },
        ),
        migrations.CreateModel(
            name='MainPageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="1920x180 o'lchamdagi asosiy sahifa banner rasmi", upload_to='banners/')),
                ('description', models.JSONField(default=dict, help_text='Har xil tillarda rasm tavsifi (JSON formatda)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asosiy sahifa banneri',
                'verbose_name_plural': 'Asosiy sahifa bannerlari',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=dict, help_text='Har xil tillarda yangiliklar sarlavhasi (JSON formatda)')),
                ('content', models.JSONField(default=dict, help_text='Har xil tillarda yangilik mazmuni (JSON formatda)')),
                ('image', models.ImageField(blank=True, help_text='Yangiliklar rasmi', null=True, upload_to='news_images/')),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='Chop etilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Oxirgi tahrir qilingan sana')),
                ('is_published', models.BooleanField(default=False, help_text='Chop etilganmi?')),
                ('views_count', models.PositiveIntegerField(default=0, help_text="Yangilik qancha marta ko'rilgan")),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=dict, help_text='Har xil tillarda hamkor nomi (JSON formatda)')),
                ('description', models.JSONField(default=dict, help_text='Har xil tillarda hamkor tavsifi (JSON formatda)')),
                ('logo', models.ImageField(blank=True, help_text='Hamkorning logotipi', null=True, upload_to='partners/')),
                ('website_url', models.URLField(blank=True, help_text='Hamkorning veb-sayti manzili', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Chop etilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Oxirgi tahrir qilingan sana')),
                ('is_active', models.BooleanField(default=True, help_text='Hamkor faolmi?')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='Sayt nomini kiriting', max_length=255)),
                ('logo_dark', models.ImageField(blank=True, help_text='Dark rejim uchun logotip', null=True, upload_to='logos/')),
                ('logo_light', models.ImageField(blank=True, help_text='Light rejim uchun logotip', null=True, upload_to='logos/')),
                ('contact_email', models.EmailField(blank=True, help_text='Aloqa uchun email manzil', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Aloqa uchun telefon raqami', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Kompaniya manzili', null=True)),
                ('maintenance_mode', models.BooleanField(default=False, help_text="Saytni texnik xizmat ko'rsatish rejimiga o'tkazish")),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook sahifa URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter sahifa URL', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram sahifa URL', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn sahifa URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt Sozlamalari',
                'verbose_name_plural': 'Sayt Sozlamalari',
            },
        ),
    ]
