# Generated by Django 5.0.6 on 2025-02-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='linkedin_url',
            new_name='telegram_url',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='twitter_url',
            new_name='youtube_url',
        ),
    ]
