# Generated by Django 5.0.6 on 2025-02-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_sitesettings_working_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCheckupApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism va familiya')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon raqami')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': "Tibbiy ko'rik arizasi",
                'verbose_name_plural': "Tibbiy ko'rik arizalari",
            },
        ),
    ]
