# Generated by Django 5.0.6 on 2025-02-26 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_medicalcheckupapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Foydalanuvchining to'liq ismi", max_length=255)),
                ('phone_number', models.CharField(help_text='Foydalanuvchining telefon raqami', max_length=20)),
                ('text', models.TextField(help_text='Izoh matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Izoh qoldirilgan sana')),
                ('news', models.ForeignKey(help_text='Izoh berilgan yangilik', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='medical.news')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
