# Generated by Django 5.0.6 on 2025-03-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalcheckupapplication',
            options={'ordering': ['-created_at'], 'verbose_name': "Tibbiy ko'rik arizasi", 'verbose_name_plural': "Tibbiy ko'rik arizalari"},
        ),
        migrations.AddField(
            model_name='medicalcheckupapplication',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='Ko‘rildi'),
        ),
    ]
