# Generated by Django 5.0.6 on 2025-03-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_alter_medicalcheckupapplication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
