# Generated by Django 5.0.6 on 2025-03-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_remove_comment_news_remove_news_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=dict, help_text='Har xil tillarda qurilma nomi (JSON formatda)')),
                ('description', models.JSONField(default=dict, help_text="Har xil tillarda qurilma haqida batafsil ma'lumot (JSON formatda)")),
                ('image', models.ImageField(help_text="Qurilma rasmi (masalan, 800x600 o'lchamda)", upload_to='equipment/')),
                ('is_active', models.BooleanField(default=True, help_text='Qurilma faol yoki faol emasligini belgilaydi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Klinika qurilmasi',
                'verbose_name_plural': 'Klinika qurilmalari',
            },
        ),
    ]
