# Generated by Django 5.0.6 on 2025-03-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_clinicequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=dict, help_text='Har xil tillarda video sarlavhasi (JSON formatda)')),
                ('url', models.URLField(help_text='Video URL (YouTube, Vimeo va boshqalar)', max_length=255)),
                ('description', models.JSONField(default=dict, help_text='Har xil tillarda video tavsifi (JSON formatda)')),
                ('is_active', models.BooleanField(default=True, help_text='Video faol yoki faol emasligini belgilaydi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
            },
        ),
    ]
