# Generated by Django 5.0.6 on 2025-03-06 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_remove_video_description_remove_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.CharField(help_text='YouTube video ID (masalan, 07NL6SlDRUY)', max_length=50, validators=[django.core.validators.RegexValidator(message='To‘g‘ri YouTube embed URL kiriting (masalan, https://www.youtube.com/embed/VIDEO_ID).', regex='(?:https?:\\/\\/)?(?:www\\.)?(?:youtube\\.com\\/embed\\/|youtu\\.be\\/)([A-Za-z0-9_-]+)')]),
        ),
    ]
