# Generated by Django 5.0.6 on 2025-03-06 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_alter_video_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.CharField(help_text='YouTube video ID (masalan, 07NL6SlDRUY)', max_length=50, validators=[django.core.validators.RegexValidator(message='To‘g‘ri YouTube URL yoki Video ID kiriting (masalan, https://www.youtube.com/embed/07NL6SlDRUY yoki 07NL6SlDRUY).', regex='(?:https?:\\/\\/)?(?:www\\.)?(?:youtube\\.com\\/(?:embed\\/|watch\\?v=)|youtu\\.be\\/)([A-Za-z0-9_-]+)')]),
        ),
    ]
