# Generated by Django 5.1.7 on 2025-10-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_alter_video_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='video1',
            field=models.FileField(blank=True, help_text='1-video faylni yuklang', null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='video2',
            field=models.FileField(blank=True, help_text='2-video faylni yuklang', null=True, upload_to='videos/'),
        ),
    ]
