# Generated by Django 5.1.7 on 2025-12-05 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0014_sitesettings_video1_sitesettings_video2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.CharField(help_text='YouTube video ID yoki URL (masalan, 07NL6SlDRUY yoki https://youtu.be/07NL6SlDRUY)', max_length=50, validators=[django.core.validators.RegexValidator(message='To‘g‘ri YouTube URL yoki Video ID kiriting (masalan, https://www.youtube.com/embed/07NL6SlDRUY yoki 07NL6SlDRUY).', regex='(?:https?:\\/\\/)?(?:www\\.)?(?:youtube\\.com\\/(?:embed\\/|watch\\?v=|shorts\\/)|youtu\\.be\\/)?([A-Za-z0-9_-]{11})')]),
        ),
    ]
