# Generated by Django 5.1.7 on 2025-12-05 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0015_alter_video_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.CharField(help_text='YouTube video ID yoki URL (masalan, 3V0SztVfsMo yoki https://youtu.be/3V0SztVfsMo)', max_length=50, validators=[django.core.validators.RegexValidator(message='To‘g‘ri YouTube URL yoki Video ID kiriting.', regex='.+')]),
        ),
    ]
