# Generated by Django 5.1.7 on 2026-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_alter_video_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcheckupapplication',
            name='phone_number',
            field=models.CharField(max_length=25, verbose_name='Telefon raqami'),
        ),
    ]
