# Generated by Django 5.0.6 on 2025-01-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('status_code', models.IntegerField()),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
