# Generated by Django 5.1.5 on 2025-01-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='global_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
