# Generated by Django 5.1.5 on 2025-01-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_log_global_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='global_ip',
        ),
    ]
