# Generated by Django 5.0.6 on 2025-02-26 12:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('job_title', models.CharField(blank=True, help_text='Lavozim', max_length=100)),
                ('department', models.CharField(blank=True, help_text="Bo'lim", max_length=100)),
                ('employee_id', models.CharField(blank=True, help_text='Xodim ID', max_length=50, null=True, unique=True)),
                ('employment_date', models.DateField(blank=True, help_text='Ish boshlash sanasi', null=True)),
                ('contract_end_date', models.DateField(blank=True, help_text='Shartnoma tugash sanasi', null=True)),
                ('is_active_employee', models.BooleanField(default=True, help_text='Faol xodimmi?')),
                ('medical_specialty', models.CharField(blank=True, help_text='Tibbiyot mutaxassisligi', max_length=100)),
                ('professional_license_number', models.CharField(blank=True, help_text='Litsenziya raqami', max_length=100)),
                ('shift_schedule', models.CharField(blank=True, help_text='Ish jadvali', max_length=100)),
                ('work_start_time', models.TimeField(blank=True, help_text='Ish boshlanish vaqti', null=True)),
                ('work_end_time', models.TimeField(blank=True, help_text='Ish tugash vaqti', null=True)),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank hisob raqami', max_length=50)),
                ('tax_identification_number', models.CharField(blank=True, help_text='STIR', max_length=20)),
                ('insurance_number', models.CharField(blank=True, help_text="Sug'urta raqami", max_length=50)),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram foydalanuvchi nomi', max_length=100)),
                ('instagram_username', models.CharField(blank=True, help_text='Instagram foydalanuvchi nomi', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Foydalanuvchi faol yoki faol emas')),
                ('is_staff', models.BooleanField(default=False, help_text='Admin sahifasiga kira oladimi?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Foydalanuvchi ismi familiyasi', max_length=255)),
                ('phone_number', models.CharField(help_text='Telefon raqami', max_length=15)),
                ('message', models.TextField(help_text='So‘rov')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan sana')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('canceled', 'Bekor qilingan')], default='pending', help_text='Qabul holati', max_length=20)),
                ('employee', models.ForeignKey(help_text='Qabul qiluvchi hodim', limit_choices_to={'is_active_employee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qabul',
                'verbose_name_plural': 'Qabullar',
                'ordering': ['-created_at'],
            },
        ),
    ]
