# Generated by Django 5.0.6 on 2025-01-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(blank=True, default=1, help_text='Bank hisob raqami', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, default=1, help_text="Bo'lim", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='emergency_contact',
            field=models.CharField(blank=True, default=3, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Xodim ID', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employment_date',
            field=models.DateField(blank=True, help_text='Ish boshlash sanasi', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='insurance_number',
            field=models.CharField(blank=True, help_text="Sug'urta raqami", max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Foydalanuvchi faol yoki faol emas'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active_employee',
            field=models.BooleanField(default=True, help_text='Faol xodimmi?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Admin sahifasiga kira oladimi?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, help_text='Lavozim', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='medical_specialty',
            field=models.CharField(blank=True, help_text='Tibbiyot mutaxassisligi', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='professional_license_number',
            field=models.CharField(blank=True, help_text='Litsenziya raqami', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shift_schedule',
            field=models.CharField(blank=True, help_text='Ish jadvali', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tax_identification_number',
            field=models.CharField(blank=True, help_text='STIR', max_length=20),
        ),
    ]
