# Generated by Django 5.0.6 on 2025-03-01 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(help_text='Malaka oshirish kursining nomi', max_length=255)),
                ('training_date', models.DateField(help_text='Malaka oshirish sanasi')),
                ('certificate_picture', models.ImageField(blank=True, help_text='Sertifikat rasmi', null=True, upload_to='training_certificates/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Malaka oshirish tarixi',
                'verbose_name_plural': 'Malaka oshirish tarixlari',
            },
        ),
    ]
