# Generated by Django 5.1.7 on 2026-04-21 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(default='Doctor A Bot', max_length=120)),
                ('bot_token', models.CharField(blank=True, help_text='Telegram bot tokenini kiriting', max_length=255)),
                ('chat_id', models.CharField(blank=True, help_text='Kanal username yoki chat ID. Masalan: @Doctor_a_HOSPITAL', max_length=255)),
                ('parse_mode', models.CharField(blank=True, choices=[('HTML', 'HTML'), ('Markdown', 'Markdown'), ('MarkdownV2', 'MarkdownV2'), ('', 'Oddiy matn')], default='HTML', help_text='Xabarlarni qanday formatda yuborishni tanlang', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Bot tizim xabarlarini yuborishi mumkin')),
                ('notes', models.TextField(blank=True, help_text='Bot haqida ichki izohlar')),
                ('last_status', models.CharField(choices=[('unknown', "Noma'lum"), ('success', 'Muvaffaqiyatli'), ('error', 'Xato'), ('skipped', "O'tkazib yuborildi")], default='unknown', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('last_response', models.JSONField(blank=True, default=dict)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot sozlamasi',
                'verbose_name_plural': 'Bot sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='BotDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('notification', 'Tizim xabari'), ('test', 'Sinov xabari'), ('manual', "Qo'lda yuborilgan")], default='notification', max_length=20)),
                ('status', models.CharField(choices=[('unknown', "Noma'lum"), ('success', 'Muvaffaqiyatli'), ('error', 'Xato'), ('skipped', "O'tkazib yuborildi")], default='unknown', max_length=20)),
                ('target_chat_id', models.CharField(blank=True, max_length=255)),
                ('message_preview', models.TextField(blank=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='bot.botsettings')),
            ],
            options={
                'verbose_name': "Bot jo'natish logi",
                'verbose_name_plural': "Bot jo'natish loglari",
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
