# Generated by Django 5.1.7 on 2026-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('chat_title', models.CharField(blank=True, max_length=255)),
                ('chat_username', models.CharField(blank=True, max_length=255)),
                ('chat_type', models.CharField(blank=True, max_length=50)),
                ('member_status', models.CharField(choices=[('unknown', "Noma'lum"), ('creator', 'Ega'), ('administrator', 'Administrator'), ('member', "A'zo"), ('restricted', 'Cheklangan'), ('left', 'Chiqib ketgan'), ('kicked', 'Bloklangan'), ('not_found', 'Topilmadi'), ('error', 'Xato')], default='unknown', max_length=32)),
                ('is_bot_admin', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot kanali',
                'verbose_name_plural': 'Bot kanallari',
                'ordering': ['label', 'chat_title', 'chat_id'],
            },
        ),
    ]
