# Generated by Django 5.1.7 on 2026-04-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botchannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTelegramUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(unique=True)),
                ('update_type', models.CharField(blank=True, max_length=64)),
                ('chat_id', models.CharField(blank=True, max_length=255)),
                ('chat_title', models.CharField(blank=True, max_length=255)),
                ('chat_username', models.CharField(blank=True, max_length=255)),
                ('chat_type', models.CharField(blank=True, max_length=50)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('message_date', models.DateTimeField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('has_photo', models.BooleanField(default=False)),
                ('has_reply_markup', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram update',
                'verbose_name_plural': "Telegram update'lar",
                'ordering': ['-update_id'],
            },
        ),
    ]
