# Generated by Django 5.1.7 on 2026-04-21 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_bottelegramupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='default_publish_channel',
            field=models.ForeignKey(blank=True, help_text='Bot orqali kelgan fayllar yuboriladigan asosiy kanal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_settings', to='bot.botchannel'),
        ),
        migrations.CreateModel(
            name='BotFileSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('awaiting_id', 'ID kutilmoqda'), ('published', 'Yuborilgan'), ('error', 'Xato')], default='awaiting_id', max_length=24)),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=255)),
                ('telegram_first_name', models.CharField(blank=True, max_length=255)),
                ('telegram_last_name', models.CharField(blank=True, max_length=255)),
                ('source_chat_id', models.CharField(blank=True, max_length=255)),
                ('source_message_id', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_id', models.CharField(blank=True, max_length=512)),
                ('file_unique_id', models.CharField(blank=True, max_length=255)),
                ('original_text', models.TextField(blank=True)),
                ('target_chat_id', models.CharField(blank=True, max_length=255)),
                ('target_message_id', models.BigIntegerField(blank=True, null=True)),
                ('generated_caption', models.TextField(blank=True)),
                ('error_text', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_submissions', to='bot.botchannel')),
            ],
            options={
                'verbose_name': 'Bot fayl yozuvi',
                'verbose_name_plural': 'Bot fayl yozuvlari',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
