# Generated by Django 5.1.7 on 2026-04-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botsettings_default_publish_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottelegramupdate',
            name='workflow_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bottelegramupdate',
            name='workflow_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bottelegramupdate',
            name='workflow_status',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
