# Generated by Django 5.1.7 on 2026-04-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_bottelegramupdate_workflow_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botfilesubmission',
            name='publish_method',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='botfilesubmission',
            name='target_meta_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
