# Generated by Django 5.1.7 on 2026-04-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_botfilesubmission_publish_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botchannel",
            name="send_as_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="botchannel",
            name="send_as_peer_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="botchannel",
            name="send_as_peer_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="telegram_desktop_account_index",
            field=models.IntegerField(default=-1, help_text="Qaysi Telegram Desktop akkaunti ishlatilishi. -1 bo'lsa aktiv akkaunt tanlanadi."),
        ),
        migrations.AddField(
            model_name="botsettings",
            name="telegram_desktop_path",
            field=models.CharField(blank=True, help_text="Telegram Desktop tdata papkasi. Bo'sh qoldirilsa standart yo'l ishlatiladi.", max_length=500),
        ),
    ]
