# Generated by Django 5.1.7 on 2026-04-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_botchannel_send_as_label_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botchannel",
            name="send_as_label",
        ),
        migrations.RemoveField(
            model_name="botchannel",
            name="send_as_peer_id",
        ),
        migrations.RemoveField(
            model_name="botchannel",
            name="send_as_peer_type",
        ),
        migrations.RemoveField(
            model_name="botsettings",
            name="telegram_desktop_account_index",
        ),
        migrations.RemoveField(
            model_name="botsettings",
            name="telegram_desktop_path",
        ),
    ]
